export const ADD_CIRCLE_REQUEST = "ADD_CIRCLE_REQUEST";
export const ADD_CIRCLE_SUCCESS = "ADD_CIRCLE_SUCCESS";
export const ADD_CIRCLE_FAIL = "ADD_CIRCLE_FAIL";

export const GET_CIRCLES_REQUEST = "GET_CIRCLES_REQUEST";
export const GET_CIRCLES_SUCCESS = "GET_CIRCLES_SUCCESS";
export const GET_CIRCLES_FAIL = "GET_CIRCLES_FAIL";
