export const ADD_CONTACT_FIRST_REQUEST = "ADD_CONTACT_FIRST_REQUEST";
export const ADD_CONTACT_FIRST_SUCCESS = "ADD_CONTACT_FIRST_SUCCESS";
export const ADD_CONTACT_FIRST_FAIL = "ADD_CONTACT_FIRST_FAIL";

export const ADD_CONTACT_SECOND_REQUEST = "ADD_CONTACT_SECOND_REQUEST";
export const ADD_CONTACT_SECOND_SUCCESS = "ADD_CONTACT_SECOND_SUCCESS";
export const ADD_CONTACT_SECOND_FAIL = "ADD_CONTACT_SECOND_FAIL";
